apiVersion: apps/v1
kind: Deployment
metadata:
  name: batte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batte
  template:
    metadata:
      labels:
        app: batte
    spec:
      containers:
      - image: okteto.dev/batte:latest
        name: batte
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ac103e06-6591-4459-9058-4e58a194579d"
        - name: Vless_Path
          value: "/vl345"
        - name: Vmess_UUID
          value: "ac103e06-6591-4459-9058-4e58a194579d"
        - name: Vmess_Path
          value: "/vm678"
        - name: Share_Path
          value: "/v2link"
